#!/bin/bash

echo "Running Prettier... ✨"

# Run Prettier command to format all files
npx prettier --write .

echo "Amending latest commit with Prettier changes..."

# Add all files to the staging area
git add .

# Amend the previous commit with the changes
git commit --amend --no-edit

echo "Prettier run complete ✅"

exit 0
